### ISSUE TITLE
Optional dependencies unclear

### ISSUE THREAD

**Issue by TomNicholas** [tomwhite/cubed#165]
Cubed has a lot of optional dependencies (some for progress bars and DAG visualization, but lots for different executors), and it's not very clear what they all are.

For example I know some package is required to get the progress bars to actually render usefully in a notebook environment (otherwise they just print once as unchanging ascii like this)
```
array-003:   0%|          | 0/1 [00:00<?, ?it/s]
```
but because the optional dependencies aren't listed anywhere I can't easily find out what package I need for this.

Related - if someone wants to try out cubed on multiple runtimes they will probably want a conda env that works for all those, and we might want to just hand them that.

(Apologies if this is already listed somewhere and I just couldn't find it!)

**Comment by tomwhite** [comment]
We can definitely improve this - the optional dependencies are not clearly organised.

* The required dependencies are listed in [setup.cfg](https://github.com/tomwhite/cubed/blob/74145fb826d21496ca86b4e64b0fcb1c55d8a931/setup.cfg#L23-L32)
* The dependencies for running the tests are in [requirements.txt](https://github.com/tomwhite/cubed/blob/74145fb826d21496ca86b4e64b0fcb1c55d8a931/requirements.txt), and in addition to the required dependencies include
   * Executor dependencies (`apache-beam`, `lithops`)
   * Testing dependencies (`pytest`)
   * Filesystems (`s3fs`)
   * Progress bars (`tqdm`)
   * Array persistence (`dill`)
* Dependencies for running modal tests are in [requirements-modal.txt](https://github.com/tomwhite/cubed/blob/74145fb826d21496ca86b4e64b0fcb1c55d8a931/requirements-modal.txt). I originally split this out since the modal dependencies clashed with the beam ones.

How about we add some "extras" (https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies)? One for each of the executors `apache-beam`, `lithops`, `modal` probably makes sense to start with. These could then be used by the tests and also users, e.g. `pip install cubed[modal]`

**Comment by TomNicholas** [comment]
Sounds good. I've had a crack at organising this in #168

**Comment by tomwhite** [comment]
Fixed in #168
