### ISSUE TITLE
Rename memory settings

### ISSUE THREAD

**Issue by tomwhite** [tomwhite/cubed#167]
@TomNicholas said in https://github.com/tomwhite/cubed/issues/160#issuecomment-1533846337

> As an aside I find it a bit confusing that `max_mem` sometimes means "maximum memory the computation is allowed to use" (i.e. actual usage) and sometimes means "maximum memory the computation is projected to use" (i.e. a conservative estimate). For example the DAG visualization just shows me the number I entered as `max_mem`, which isn't particularly helpful here. It would be more helpful if it showed two numbers, i.e. `projected_memory_use / max_allowed_mem`, so I can see if I will exceed it or how much headroom I have.

See also #58

**Comment by tomwhite** [comment]
How about renaming `max_mem` to `allowed_mem` and `required_mem` to `projected_mem`?

**Comment by tomwhite** [comment]
I'm toying with the idea of whether to include `reserved_mem` in the `allowed_mem` and `projected_mem` numbers.

As shown on https://tom-e-white.com/cubed/computation.html#memory, "`reserved_mem` is the amount of memory reserved on a worker for non-data use - it’s whatever is needed by the Python process for running a task". The reason to include it in `allowed_mem` is because when you specify memory limits in runtime systems like Lithops, Modal, and Beam you give a total for what your tasks need, which includes the part for holding the arrays in memory, and the non-data part.

If we did this, then we'd have the following invariant:

```
measured_mem <= projected_mem <= allowed_mem
```

rather than

```
measured_mem <= projected_mem + reserved_mem <= allowed_mem + reserved_mem
```

This would mean that figures for `projected_mem` in the visualization and so on might be a bit harder to unpick because they would include `reserved_mem`, but if we showed that value too then maybe it would be OK.

Note that the user has to specify `reserved_mem`, since it varies by runtime, and basically has to be measured (by calling `measure_reserved_memory`). We might be able to come up conservative defaults for different runtimes though (e.g. I just measured Lithops as 38MB).

(Also perhaps `reserved_mem` would be better named `runtime_overhead_mem`?)

Any thougths @TomNicholas?

**Comment by TomNicholas** [comment]
> The reason to include it in `allowed_mem` is because when you specify memory limits in runtime systems like Lithops, Modal, and Beam you give a total for what your tasks need, which includes the part for holding the arrays in memory, and the non-data part.

This makes sense. Many users won't immediately appreciate this distinction, and will probably first try just setting `allowed_mem` to their total RAM. (cubed could maybe then even measure the system RAM, and default `allowed_mem` to 80% of it or something...)

> we'd have the following invariant

I like that a lot.

> This would mean that figures for projected_mem in the visualization and so on might be a bit harder to unpick because they would include reserved_mem, but if we showed that value too then maybe it would be OK.

I don't think that's a big problem. You could imagine showing a color-coded filled line chart, something like this

![image](https://github.com/tomwhite/cubed/assets/35968931/0eaa2c43-75b1-4336-af34-ecb6e0b38263)

It's a bit awkward also because `runtime_overhead_mem` is projected rather than measured. If you were able to measure `reserved_mem` (or "overhead_mem") dynamically it would look more like this

![image](https://github.com/tomwhite/cubed/assets/35968931/4944c4f5-5e53-4eb4-8872-fd69febf9587)

([gist for both plots](https://gist.github.com/TomNicholas/3ae6975397605cd94166b8cd052f8280))

> (Also perhaps reserved_mem would be better named runtime_overhead_mem?)

I prefer that term, though `reserved` does get across the idea that you set it rather than it being measured. Really it's the "reserved memory for runtime overhead" isn't it.

**Comment by tomwhite** [comment]
Great diagrams! I have tried to add something like this #180.
